## Data Overview

This section introduces the dataset used in this notebook. It summarizes the dataset’s source, size, key variables, and data types, and notes any relevant limitations or data-quality considerations. These details provide context for the analysis that follows.

In [2]:
import pandas as pd
import sqlite3

In [3]:
customers = pd.read_csv("../../data/raw/customers.csv")
accounts = pd.read_csv("../../data/raw/accounts.csv")
transactions = pd.read_csv("../../data/raw/transactions.csv")
loans = pd.read_csv("../../data/raw/loans.csv")

In [4]:
transactions.head()  # first 5 rows

,transaction_id,account_id,amount,category,ts,is_fraud
0,1,1210,19.27,leisure,2024-01-22 08:04:32,False
1,2,200,4.78,rent,2024-08-01 04:32:50,False
2,3,122,37.84,groceries,2024-05-28 09:53:03,False
3,4,1010,12.77,leisure,2024-06-25 01:42:18,False
4,5,245,18.57,leisure,2024-01-24 15:40:29,False

In [5]:
transactions.shape  # (rows, columns)

(10000, 6)

In [6]:
transactions.info()      # types et valeurs manquantes

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  10000 non-null  int64
 1   account_id      10000 non-null  int64
 2   amount          10000 non-null  float64
 3   category        10000 non-null  str
 4   ts              10000 non-null  str
 5   is_fraud        10000 non-null  bool
dtypes: bool(1), float64(1), int64(2), str(2)
memory usage: 400.5 KB

In [7]:
transactions.describe()  # Basic statistics

       transaction_id    account_id        amount
count     10000.00000  10000.000000  10000.000000
mean       5000.50000    644.925400     55.234429
std        2886.89568    373.533023     73.658874
min           1.00000      1.000000      0.680000
25%        2500.75000    325.750000     16.975000
50%        5000.50000    645.000000     32.820000
75%        7500.25000    965.000000     64.920000
max       10000.00000   1300.000000   2103.250000

In [8]:
# 2. Open the database connection
con = sqlite3.connect("../../data/nordbank.db")

In [9]:
# 3. Copier chaque tableau pandas dans une table SQL
customers.to_sql("customers", con, if_exists="replace", index=False)
accounts.to_sql("accounts", con, if_exists="replace", index=False)
transactions.to_sql("transactions", con, if_exists="replace", index=False)
loans.to_sql("loans", con, if_exists="replace", index=False)

333